### ISSUE TITLE
Purpose of clip time padding?

### ISSUE THREAD

**Issue by RSKothari** [cvdfoundation/ava-dataset#6]
Hello, the extraction code provided [here](http://thoth.inrialpes.fr/ava/getava.php) has a variable called `clip_time_padding`. What is the purpose of that variable?

**Comment by ross-da** [comment]
I'm not the author of that code, but it seems to pad the extracted clip by an extra 1s before and after. Perhaps this could be due to ffmpeg decoding issues... I have seen decoding from an arbitrary start point produce garbled images until it reaches a video encoding keyframe, but I'll leave that to video codec experts to explain.

**Comment by RSKothari** [comment]
I see. Thanks David, so it seems that we would pretty much need to eyeball the exacted frame in the clip which matches with the previously extracted mid frame.
